// eslint-disable-next-line
export default {
  ADD_TICKET: "ADD_TICKET",
  GET_TICKETS: "GET_TICKETS",
  GET_USER_TICKETS: "GET_USER_TICKETS",
  UPDATE_TICKET: "UPDATE_TICKET",
  CLEAR_TICKETS: "CLEAR_TICKETS",
  DEL_TICKET: "DEL_TICKET",
  ADD_CATEGORY: "ADD_CATEGORY",
  GET_CATEGORIES: "GET_CATEGORIES",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DEL_CATEGORY: "DEL_CATEGORY",
  ADD_USER: "ADD_USER",
  GET_USER: "GET_USER",
};
